### ISSUE TITLE
Issue with Faker on Enums

### ISSUE THREAD

**Issue by ToferC** [cksac/fake-rs#35]
I'm receiving the following error when trying to use Dummy trait on a struct that contains an emum. 

```rust
proc-macro derive panicked

help: message: called `Result::unwrap()` on an `Err` value: Error { kind: UnsupportedShape("enum"), locations: [], span: None }
```

From reviewing the crate, it seems like enums should be "fakeable", but minor tweaking doesn't help. If this is not the case, a use case on implementing the `Dummy` Trait would be great to have in the docs or examples.

**Comment by cksac** [comment]
Hi @ToferC,  `Dummy` derive macro is not support enum yet. you can implement by hand like below,

```rust
use fake::{Dummy, Fake, Faker};
use rand::Rng;

enum Animal {
    Dog,
    Cat,
}

impl Dummy<Faker> for Animal {
    fn dummy_with_rng<R: Rng + ?Sized>(_: &Faker, rng: &mut R) -> Self {
        if Faker.fake_with_rng::<bool>(rng)) {
           Animal::Dog
        } else {
           Animal::Cat
        }
    }
}
```
other impls [examples](https://github.com/cksac/fake-rs/blob/master/fake/src/impls/http/mod.rs)

**Comment by ToferC** [comment]
Thanks very much for the explanation and the pointer. I ended up implementing a work around using `Distribution`, but I'll go back and update to use the macros. Much appreciated!

```rust
#[derive(Serialize, Deserialize, Debug)]
/// Represents the person's ethnic identification.
pub enum Ethnicity {
    Asian,
    Black,
    Caucasian,
    HispanicLatinx,
    Indigenous,
    Other(String),
    NoAnswer,
}

impl Distribution<Ethnicity> for Standard {
    fn sample<R: Rng + ?Sized>(&self, rng: &mut R) -> Ethnicity {
        match rng.gen_range(0, 6) {
            0 => Ethnicity::Asian,
            1 => Ethnicity::Black,
            2 => Ethnicity::Caucasian,
            3 => Ethnicity::Caucasian,
            4 => Ethnicity::Indigenous,
            5 => Ethnicity::Other( String::from("Maui") ),
            6 => Ethnicity::NoAnswer,
            _ => Ethnicity::NoAnswer,
        }
    }
}
```

**Comment by cksac** [comment]
Hi @ToferC , I pushed new version 2.2.3 with Dummy derived macro to support enum. see [examples](https://github.com/cksac/fake-rs/blob/master/fake/examples/derive.rs)

**Comment by ToferC** [comment]
This looks amazing @cksac - Thank yiu and thanks for the great crate. I'll check it out tomorrow!

**Comment by ToferC** [comment]
Hi @cksac - I've updated to 2.2.3, but am still getting the error on enums:

```rust
proc-macro derive panicked

help: message: called `Result::unwrap()` on an `Err` value: Error { kind: UnsupportedShape("enum"), locations: [], span: None }
```

There might be an issue with the code, I'm developing, but they are pretty vanilla enums for the most part: https://github.com/ToferC/learner_models/blob/master/src/models/demographic.rs

**Comment by cksac** [comment]
please try run `cargo update` then run again

**Comment by ToferC** [comment]
🤦
